# -*- coding: utf-8 -*-
"""Migrate remaining non-sun- CSS class names in html/ejs/js."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

REPLACEMENTS = [
    ("class=\"sun-warningBox hidden\"", 'class="sun-warningBox sun-hidden"'),
    (" buttonsPanel", " sun-buttonsPanel"),
    (" tabButtonsFramed", " sun-tabButtonsFramed"),
    (" compact", " sun-compact"),
    (" dateComparisonViewTab", " sun-dateComparisonViewTab"),
    ('class="sun-tabButton active"', 'class="sun-tabButton sun-active"'),
    (".classList.add('active')", ".classList.add('sun-active')"),
    (".classList.remove('active')", ".classList.remove('sun-active')"),
    ('.classList.toggle("active"', '.classList.toggle("sun-active"'),
    (".classList.toggle('active'", ".classList.toggle('sun-active'"),
    (".removeClass('active')", ".removeClass('sun-active'"),
    (".addClass('active')", ".addClass('sun-active'"),
    ('class="sun-cornerSquare tl"', 'class="sun-cornerSquare sun-cornerPosTl"'),
    ('class="sun-cornerSquare tr"', 'class="sun-cornerSquare sun-cornerPosTr"'),
    ('class="sun-cornerSquare bl"', 'class="sun-cornerSquare sun-cornerPosBl"'),
    ('class="sun-cornerSquare br"', 'class="sun-cornerSquare sun-cornerPosBr"'),
    ('class="sun-cornerSquare tc"', 'class="sun-cornerSquare sun-cornerPosTc"'),
    ('class="sun-cornerSquare bc"', 'class="sun-cornerSquare sun-cornerPosBc"'),
    ('class="sun-cornerSquare lc"', 'class="sun-cornerSquare sun-cornerPosLc"'),
    ('class="sun-cornerSquare rc"', 'class="sun-cornerSquare sun-cornerPosRc"'),
    ('class="sun-cornerSquare mt"', 'class="sun-cornerSquare sun-cornerPosMt"'),
    ('class="sun-cornerSquare mb"', 'class="sun-cornerSquare sun-cornerPosMb"'),
    ('class="sun-cornerSquare ml"', 'class="sun-cornerSquare sun-cornerPosMl"'),
    ('class="sun-cornerSquare mr"', 'class="sun-cornerSquare sun-cornerPosMr"'),
    ('class="sun-cornerSquare mt2"', 'class="sun-cornerSquare sun-cornerPosMt2"'),
    ('class="sun-cornerSquare mb2"', 'class="sun-cornerSquare sun-cornerPosMb2"'),
    ('class="sun-cornerSquare ml2"', 'class="sun-cornerSquare sun-cornerPosMl2"'),
    ('class="sun-cornerSquare mr2"', 'class="sun-cornerSquare sun-cornerPosMr2"'),
    ("'.tl'", "'.sun-cornerPosTl'"),
    ("'.tr'", "'.sun-cornerPosTr'"),
    ("'.bl'", "'.sun-cornerPosBl'"),
    ("'.br'", "'.sun-cornerPosBr'"),
    ("'.tc'", "'.sun-cornerPosTc'"),
    ("'.bc'", "'.sun-cornerPosBc'"),
    ("'.lc'", "'.sun-cornerPosLc'"),
    ("'.rc'", "'.sun-cornerPosRc'"),
    ("'.mt'", "'.sun-cornerPosMt'"),
    ("'.mb'", "'.sun-cornerPosMb'"),
    ("'.ml'", "'.sun-cornerPosMl'"),
    ("'.mr'", "'.sun-cornerPosMr'"),
    ("'.mt2'", "'.sun-cornerPosMt2'"),
    ("'.mb2'", "'.sun-cornerPosMb2'"),
    ("'.ml2'", "'.sun-cornerPosMl2'"),
    ("'.mr2'", "'.sun-cornerPosMr2'"),
    ("class=\"date-name\"", 'class="sun-dateName"'),
    (" date-name\"", ' sun-dateName"'),
    ("class=\"date-name ", 'class="sun-dateName '),
    (".date-name", ".sun-dateName"),
    ("date-name-edit", "sun-dateNameEdit"),
    ("date-star", "sun-dateStar"),
    ("date-selection-checks", "sun-dateSelectionChecks"),
    ("date-checkbox", "sun-dateCheckbox"),
    ("date-gender-badge", "sun-dateGenderBadge"),
    ("dateDragHandle", "sun-dateDragHandle"),
    ("date-gender-select", "sun-dateGenderSelect"),
    ("date-description-edit", "sun-dateDescriptionEdit"),
    ("date-input", "sun-dateInput"),
    ("wave-drag-handle", "sun-waveDragHandle"),
    ("expandCollapseBtn", "sun-expandCollapseBtn"),
    ("group-stats", "sun-groupStats"),
    ("group-stat-total", "sun-groupStatTotal"),
    ("group-stat-a", "sun-groupStatA"),
    ("group-stat-b", "sun-groupStatB"),
    ("no-waves-message", "sun-noWavesMessage"),
    ("summary-empty", "sun-summaryEmpty"),
    ("summary-item-exact", "sun-summaryItemExact"),
    ("summary-item-very-close", "sun-summaryItemVeryClose"),
    ("summary-item-fairly-close", "sun-summaryItemFairlyClose"),
    ("summary-item-very-close", "sun-summaryItemVeryClose"),
    ("summary-item-close", "sun-summaryItemClose"),
    ("summary-item-nearby", "sun-summaryItemNearby"),
    ("summary-item-info", "sun-summaryItemInfo"),
    ("summary-item-name", "sun-summaryItemName"),
    ("summary-item-index", "sun-summaryItemIndex"),
    ("summary-item-details", "sun-summaryItemDetails"),
    ("summary-item-state", "sun-summaryItemState"),
    ("summary-item-difference", "sun-summaryItemDifference"),
    ("summary-item-closeness", "sun-summaryItemCloseness"),
    ("summary-item-color", "sun-summaryItemColor"),
    ("summary-item-actions", "sun-summaryItemActions"),
    ("summary-item", "sun-summaryItem"),
    ("ui-btn", "sun-uiBtn"),
    ("show-on-vizor-btn", "sun-showOnVizorBtn"),
    ("date-compare-vizor-btn", "sun-dateCompareVizorBtn"),
    ("intersection-vizor-b-btn", "sun-intersectionVizorBBtn"),
    ("wave-direction-label", "sun-waveDirectionLabel"),
    ("intersection-stats-content", "sun-intersectionStatsContent"),
    ("list-empty", "sun-listEmpty"),
    ("intersection-result-closeness", "sun-intersectionResultCloseness"),
    ("date-comparison-table", "sun-dateComparisonTable"),
    ("date-comparison-state", "sun-dateComparisonState"),
    ("date-comparison-actions", "sun-dateComparisonActions"),
    ("date-comparison-period", "sun-dateComparisonPeriod"),
    ("date-comparison-name", "sun-dateComparisonName"),
    ("date-comparison-color", "sun-dateComparisonColor"),
    ("grid-absolute-container", "sun-gridAbsoluteContainer"),
    ("grid-static-container", "sun-gridStaticContainer"),
    ("center-name-container", "sun-centerNameContainer"),
    ("weekday-label", "sun-weekdayLabel"),
    ("wave-intersection-points", "sun-waveIntersectionPoints"),
    ("wave-intersection-point", "sun-waveIntersectionPoint"),
    ("graphAxisSwapped", "sun-graphAxisSwapped"),
    ("has-notes", "sun-hasNotes"),
    ("timeBarControlsStates", "sun-timeBarControlsStates"),
    ("timeBarControlsGroups", "sun-timeBarControlsGroups"),
    ("tabButtonsFramed", "sun-tabButtonsFramed"),
    ("spoiler-toggle", "sun-spoilerToggle"),
    ("today-active", "sun-todayActive"),
    ("flip-h-active", "sun-flipHActive"),
    ("uiBtnToggleOff", "sun-uiBtnToggleOff"),
    ("hour-marker", "sun-hourMarker"),
    (".classList.contains('weekday-label')", ".classList.contains('sun-weekdayLabel')"),
    ("'sun-listItemEditing'", "'sun-listItemEditing'"),  # noop guard
]

# list item active state (only when it's a class name, not activeDateId)
EXTRA = [
    ("row.classList.toggle('active'", "row.classList.toggle('sun-active'"),
    (" ? 'active' : ''", " ? 'sun-active' : ''"),
    ("<%= data.active ? 'active'", "<%= data.active ? 'sun-active'"),
    ("'sun-tabButtons tabButtonsFramed'", "'sun-tabButtons sun-tabButtonsFramed'"),
    ("'sun-tabButtons tabButtonsFramed'", "'sun-tabButtons sun-tabButtonsFramed'"),
    ("className = 'sun-tabButtons tabButtonsFramed'", "className = 'sun-tabButtons sun-tabButtonsFramed'"),
    (".sun-tabButtons.tabButtonsFramed", ".sun-tabButtons.sun-tabButtonsFramed"),
    (".querySelectorAll('.hour-marker.active')", ".querySelectorAll('.sun-hourMarker.sun-active')"),
    ("markers[hour].classList.add('active')", "markers[hour].classList.add('sun-active')"),
    ("marker.classList.remove('active')", "marker.classList.remove('sun-active')"),
    ("line.classList.toggle('active'", "line.classList.toggle('sun-active'"),
    ("line.classList.add('active')", "line.classList.add('sun-active'"),
    ("line.classList.remove('active')", "line.classList.remove('sun-active'"),
    ("xAxis.classList.remove('active')", "xAxis.classList.remove('sun-active'"),
    ("xAxis.classList.toggle('active'", "xAxis.classList.toggle('sun-active'"),
    ("graph.classList.toggle('graphAxisSwapped'", "graph.classList.toggle('sun-graphAxisSwapped'"),
    ("line.classList.add('has-notes')", "line.classList.add('sun-hasNotes')"),
    ("line.classList.remove('has-notes')", "line.classList.remove('sun-hasNotes')"),
    ("btn.classList.remove('ui-btn')", "btn.classList.remove('sun-uiBtn')"),
    ("timeBarManager.js", "timeBarManager.js"),
]
REPLACEMENTS.extend(EXTRA)

GLOBS = ["index.html", "templates/*.ejs", "modules/*.js"]

for pattern in GLOBS:
    for path in ROOT.glob(pattern):
        if "node_modules" in str(path):
            continue
        data = path.read_text(encoding="utf-8")
        orig = data
        for old, new in REPLACEMENTS:
            data = data.replace(old, new)
        if data != orig:
            path.write_text(data, encoding="utf-8")
            print("updated", path.relative_to(ROOT))
